name: Example workflow for Snyk Infrastructure as Code
on: 
  push:
       paths: Pluto-tv/kubernetes-goat
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Snyk
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
